# docker-compose.test.yml
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST_ADDRESS=localstack
      - DEBUG=1
    volumes:
      - "/tmp/localstack:/tmp/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health?services=s3,dynamodb"]
      interval: 15s
      start_period: 60s
      timeout: 15s
      retries: 20

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      localstack:
        condition: service_healthy
    # Start of entrypoint definition
    # 'entrypoint' is indented 4 spaces from the start of 'test:'
    entrypoint: |
      # The bash command string starts here. It must be indented MORE than 'entrypoint:'.
      # I am using 6 spaces for this line.
      /bin/bash -c "
        # The python code block is indented 8 spaces (2 more than the bash line).
        python -c '
import os
import time
import requests
import sys

# Get endpoint from environment variable, fallback for localstack service
# This line is indented 10 spaces.
endpoint = os.getenv(\"DYNAMODB_ENDPOINT\", \"http://localstack:4566\")
print(f\"Waiting for LocalStack DynamoDB and S3 at {endpoint}...\")
max_attempts = 30 # Approx 5 minutes (30 attempts * 10 seconds/attempt)
attempts = 0
while attempts < max_attempts:
    try:
        # These lines are indented 12 spaces.
        response = requests.get(f\"{endpoint}/_localstack/health?services=s3,dynamodb\")
        response.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)
        health_data = response.json().get(\"services\", {})
        s3_status = health_
