version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST_ADDRESS=localstack
      - DEBUG=1
    volumes:
      - "./.localstack:/var/lib/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health?services=s3,dynamodb"]
      interval: 15s
      start_period: 60s
      timeout: 15s
      retries: 20

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: >
      /bin/bash -c "python wait_for_localstack.py && pytest test_api.py"
