version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5050:5050"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - DYNAMODB_TABLE=PackMyBagTable
      - S3_BUCKET=packmybag-bucket
    depends_on:
      - localstack
    volumes:
      - .:/app

  localstack:
    image: localstack/localstack
    ports:
      - "4567:4566"  # External 4567 mapped to internal 4566
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/tmp/localstack"

