FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY wait_for_localstack.py wait_for_localstack.py

CMD ["pytest", "test_api.py"]
