version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5050:5050"
    env_file:
      - .env.aws
    environment:
      AWS_REGION: us-east-1
      DYNAMODB_TABLE: packing_lists
      S3_BUCKET: packmybag-artifacts-20250814

