version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      S3_BUCKET: ${S3_BUCKET}
    # Test in container, then quit
    command: >
      sh -c "python -m pytest -v --disable-warnings test_api.py"

