name: Run API tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Make test.sh executable
        run: chmod +x test.sh

      - name: Run Docker Compose test stack
        run: ./test.sh

      - name: Cleanup LocalStack directory
        if: always()
        run: |
          sudo fuser -k /tmp/localstack || true
          sudo rm -rf /tmp/localstack || true


